spring.application.name=ms-clinica-gestion
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/BD_MEDICENTER
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false